name: vehicle_management_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg:
  flutter_bloc:
  hydrated_bloc:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  google_maps_flutter:
  get_it:
  dartz:
  path_provider:
  intl: ^0.19.0
  uuid: ^4.5.0
  equatable:
  internet_connection_checker:
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  google_maps_place_picker_mb: ^3.1.2
  dropdown_button2: ^2.3.9
  geocoding: ^3.0.0
  location: ^6.0.2
  http: ^1.2.2
  dio: ^5.7.0
  logger: ^2.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/animations/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Satoshi
  #     fonts:
  #       - asset: assets/fonts/Satoshi-Black.ttf
  #         weight: 900
  #       - asset: assets/fonts/Satoshi-Bold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Satoshi-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Satoshi-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Satoshi-Light.ttf
  #         weight: 300

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
