import 'package:vehicle_management_app/data/models/vehicle/vehicle.dart';

final List<VehicleModel> sampleVehicleData = [
  VehicleModel(
    vehicleId: '1',
    registrationNumber: 'ABC123',
    name: 'Corolla',
    brand: 'Toyota',
    driverId: 'D1',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '2',
    registrationNumber: 'DEF456',
    name: 'Civic',
    brand: 'Honda',
    driverId: 'D2',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '3',
    registrationNumber: 'GHI789',
    name: 'Mustang',
    brand: 'Ford',
    driverId: 'D3',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '4',
    registrationNumber: 'JKL012',
    name: 'Camaro',
    brand: 'Chevrolet',
    driverId: 'D4',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '5',
    registrationNumber: 'MNO345',
    name: 'Altima',
    brand: 'Nissan',
    driverId: 'D5',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '6',
    registrationNumber: 'PQR678',
    name: '3 Series',
    brand: 'BMW',
    driverId: 'D6',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '7',
    registrationNumber: 'STU901',
    name: 'A4',
    brand: 'Audi',
    driverId: 'D7',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '8',
    registrationNumber: 'VWX234',
    name: 'C-Class',
    brand: 'Mercedes-Benz',
    driverId: 'D8',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '9',
    registrationNumber: 'YZA567',
    name: 'Passat',
    brand: 'Volkswagen',
    driverId: 'D9',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '10',
    registrationNumber: 'BCD890',
    name: 'Elantra',
    brand: 'Hyundai',
    driverId: 'D10',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '11',
    registrationNumber: 'EFG123',
    name: 'Optima',
    brand: 'Kia',
    driverId: 'D11',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '12',
    registrationNumber: 'HIJ456',
    name: 'Impreza',
    brand: 'Subaru',
    driverId: 'D12',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '13',
    registrationNumber: 'KLM789',
    name: '3',
    brand: 'Mazda',
    driverId: 'D13',
    availablity: 'Available',
  ),
  VehicleModel(
    vehicleId: '14',
    registrationNumber: 'NOP012',
    name: 'Model 3',
    brand: 'Tesla',
    driverId: 'D14',
    availablity: 'Unavailable',
  ),
  VehicleModel(
    vehicleId: '15',
    registrationNumber: 'QRS345',
    name: 'IS',
    brand: 'Lexus',
    driverId: 'D15',
    availablity: 'Available',
  ),
];
