import 'package:vehicle_management_app/data/models/vehicle/vehicle.dart';

final List<VehicleModel> vehicleList = [
  VehicleModel(
    vehicleId: '001',
    registrationNumber: 'CG02 AJ 0033',
    type: 'MUV',
    manufacturer: 'Toyota',
    brand: 'Innova',
    status: '',
    fuelType: 'Diesel',
    year: null,
    owner: 'CSVTU',
    user: 'HVC',
    remark: '',
    driverId: '',
    imageUrl:
        'https://imgd.aeplcdn.com/642x361/n/cw/ec/51540/toyota-innova-crysta-left-front-three-quarter0.jpeg?wm=1&q=80',
  ),
  VehicleModel(
    vehicleId: '002',
    registrationNumber: 'CG02 D 0033',
    type: 'Sedan',
    manufacturer: 'Toyota',
    brand: 'ETIOS',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: 'Pro VC',
    remark: '',
    driverId: '',
    imageUrl:
        'https://5.imimg.com/data5/AA/RB/MY-69291249/toyota-etios-28per-day-300kms-29-1000x1000.jpg',
  ),
  VehicleModel(
    vehicleId: '003',
    registrationNumber: 'CG02 AU 0554',
    type: 'Sedan',
    manufacturer: 'Suzuki',
    brand: 'CIAZ',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: 'Registrar',
    remark: '',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/370x208/n/qcu6isa_1467597.jpg?q=80',
  ),
  VehicleModel(
    vehicleId: '004',
    registrationNumber: 'CG02 AU 0556',
    type: 'Sedan',
    manufacturer: 'Suzuki',
    brand: 'CIAZ',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: '',
    remark: '',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/370x208/n/qcu6isa_1467597.jpg?q=80',
  ),
  VehicleModel(
    vehicleId: '005',
    registrationNumber: 'CG02 AU 1207',
    type: 'MUV',
    manufacturer: 'Suzuki',
    brand: 'Ertiga',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: '',
    remark: '',
    driverId: '',
    imageUrl:
        'https://stimg.cardekho.com/images/car-images/930x620/Maruti/Ertiga/8711/1650016330874/224_white_fffff.jpg?tr=w-898',
  ),
  VehicleModel(
    vehicleId: '006',
    registrationNumber: 'CG02 AU 1208',
    type: 'MUV',
    manufacturer: 'Suzuki',
    brand: 'Ertiga',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: '',
    remark: '',
    driverId: '',
    imageUrl:
        'https://stimg.cardekho.com/images/car-images/930x620/Maruti/Ertiga/8711/1650016330874/224_white_fffff.jpg?tr=w-898',
  ),
  VehicleModel(
      vehicleId: '007',
      registrationNumber: 'CG02 6925',
      type: 'MUV',
      manufacturer: 'Mahindra',
      brand: 'Bolero',
      status: 'Out of Order',
      fuelType: 'Diesel',
      remark: '4Wheels, oil total, brake, silencer replacement or repair',
      user: '',
      owner: 'CSVTU',
      driverId: '',
      imageUrl: 'https://imgd.aeplcdn.com/664x374/n/o55akva_1604753.jpg?q=80',
      year: null),
  VehicleModel(
    vehicleId: '008',
    registrationNumber: 'CG07 MB 3156',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: '',
    fuelType: 'Diesel',
    remark: '4Wheels Head lamps wind shield front',
    user: '',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/dft0asa_1458925.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '009',
    registrationNumber: 'CG07 MB 3926',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: 'Out of Order',
    fuelType: 'Diesel',
    remark:
        'Radiator, Bumper front, 4Wheels Head lamps, wind shield front, Brake, oil replacement',
    owner: 'CSVTU',
    user: '',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/dft0asa_1458925.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '010',
    registrationNumber: 'CG07 CA 4678',
    type: 'Pickup Truck',
    manufacturer: 'TATA',
    brand: '207',
    status: '',
    fuelType: 'Diesel',
    user: '',
    owner: 'CSVTU',
    driverId: '',
    imageUrl:
        'https://pickup.tatamotors.com/images/tata-pickup-trucks/features/tata-207/tata-207-pickup-truck-features.png',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '011',
    registrationNumber: 'CG02 6924',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: 'Out of Order',
    fuelType: 'Diesel',
    remark: '4wheels, brake',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/o55akva_1604753.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '012',
    registrationNumber: 'CG02 AU 1269',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    fuelType: 'Diesel',
    remark: 'Full servicing, 4wheels completed 80000km',
    owner: 'CSVTU',
    user: '',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/o55akva_1604753.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '013',
    registrationNumber: 'CG02 AU 1270',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    fuelType: 'Diesel',
    user: '',
    remark: 'Full servicing, 4wheels completed 80000km',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/o55akva_1604753.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '014',
    registrationNumber: 'CG02 AU 1268',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    user: '',
    fuelType: 'Diesel',
    remark: 'Oil total, 4wheels completed 80000km',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/o55akva_1604753.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '015',
    registrationNumber: 'CG02 AU 1267',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    user: '',
    fuelType: 'Diesel',
    remark: '2wheels',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/o55akva_1604753.jpg?q=80',
    year: null,
  ),
  VehicleModel(
    vehicleId: '016',
    registrationNumber: 'CG 07 BP 2411',
    type: 'E-Rikshaw',
    manufacturer: '',
    brand: '',
    status: 'Out of Order',
    user: '',
    fuelType: 'Electric',
    owner: 'CSVTU',
    driverId: '',
    imageUrl:
        'https://truckcdn.cardekho.com/in/mahindra/treo/mahindra-treo-67242.jpg',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '017',
    registrationNumber: 'CG02 AU 0033',
    type: 'MUV',
    manufacturer: 'Isuzu',
    brand: '',
    status: '',
    user: '',
    fuelType: 'Petrol',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/bohdicb_1710129.jpg?q=80',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '018',
    registrationNumber: 'CG04 HB 8271',
    type: 'Sedan',
    manufacturer: 'TATA',
    brand: 'Indigo',
    status: 'Out of Order',
    fuelType: 'Petrol',
    owner: 'CSVTU',
    driverId: '',
    imageUrl:
        'https://stimg.cardekho.com/images/carexteriorimages/630x420/Tata/Tata-Indigo/929/1544533656403/front-left-side-47.jpg',
    user: '',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '019',
    registrationNumber: 'CG04 H 1534',
    type: 'Sedan',
    manufacturer: 'Hyundai',
    brand: 'Elantra',
    status: 'Out of Order',
    fuelType: 'Petrol',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd-ct.aeplcdn.com/1056x660/n/nj4fmsa_1472636.jpg?q=80',
    user: '',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '020',
    registrationNumber: 'CG04 H 2213',
    type: 'Hatchback',
    manufacturer: 'Maruti',
    brand: 'Alto',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/370x208/n/fvsdora_1420344.jpg?q=80',
    user: '',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '021',
    registrationNumber: 'CG04 E 0663',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/dft0asa_1458925.jpg?q=80',
    user: '',
    remark: '',
    year: null,
  ),
  VehicleModel(
    vehicleId: '022',
    registrationNumber: 'CG07 9419',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    remark: '',
    year: null,
    imageUrl: 'https://imgd.aeplcdn.com/664x374/n/dft0asa_1458925.jpg?q=80',
    user: '',
  ),
  VehicleModel(
    vehicleId: '023',
    registrationNumber: 'CG07 9822',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Max',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    remark: "",
    year: null,
    imageUrl:
        'https://offers.caimahindra.com/uploads/product/maxx-pik-up-white.png',
    user: '',
  ),
];
