import 'package:vehicle_management_app/data/models/vehicle/vehicle.dart';

final List<VehicleModel> vehicleList = [
  VehicleModel(
    vehicleId: '001',
    registrationNumber: 'CG02 AJ 0033',
    type: 'MUV',
    manufacturer: 'Toyota',
    brand: 'Innova',
    status: '',
    fuelType: 'Diesel',
    year: null,
    owner: 'CSVTU',
    user: 'HVC',
    remark: '',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '002',
    registrationNumber: 'CG02 D 0033',
    type: 'Sedan',
    manufacturer: 'Toyota',
    brand: 'ETIOS',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: 'Pro VC',
    remark: '',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '003',
    registrationNumber: 'CG02 AU 0554',
    type: 'Sedan',
    manufacturer: 'Suzuki',
    brand: 'CIAZ',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: 'Registrar',
    remark: '',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '004',
    registrationNumber: 'CG02 AU 0556',
    type: 'Sedan',
    manufacturer: 'Suzuki',
    brand: 'CIAZ',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: '',
    remark: '',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '005',
    registrationNumber: 'CG02 AU 1207',
    type: 'MUV',
    manufacturer: 'Suzuki',
    brand: 'Ertiga',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: '',
    remark: '',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '006',
    registrationNumber: 'CG02 AU 1208',
    type: 'MUV',
    manufacturer: 'Suzuki',
    brand: 'Ertiga',
    status: '',
    fuelType: 'Petrol',
    year: null,
    owner: 'CSVTU',
    user: '',
    remark: '',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '007',
    registrationNumber: 'CG02 6925',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: 'Out of Order',
    fuelType: 'Diesel',
    remark: '4Wheels, oil total, brake, silencer replacement or repair',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '008',
    registrationNumber: 'CG07 MB 3156',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: '',
    fuelType: 'Diesel',
    remark: '4Wheels Head lamps wind shield front',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '009',
    registrationNumber: 'CG07 MB 3926',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: 'Out of Order',
    fuelType: 'Diesel',
    remark:
        'Radiator, Bumper front, 4Wheels Head lamps, wind shield front, Brake, oil replacement',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '010',
    registrationNumber: 'CG07 CA 4678',
    type: 'Pickup Truck',
    manufacturer: 'TATA',
    brand: '207',
    status: '',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '011',
    registrationNumber: 'CG02 6924',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: 'Out of Order',
    fuelType: 'Diesel',
    remark: '4wheels, brake',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '012',
    registrationNumber: 'CG02 AU 1269',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    fuelType: 'Diesel',
    remark: 'Full servicing, 4wheels completed 80000km',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '013',
    registrationNumber: 'CG02 AU 1270',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    fuelType: 'Diesel',
    remark: 'Full servicing, 4wheels completed 80000km',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '014',
    registrationNumber: 'CG02 AU 1268',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    fuelType: 'Diesel',
    remark: 'Oil total, 4wheels completed 80000km',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '015',
    registrationNumber: 'CG02 AU 1267',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Bolero',
    status: '',
    fuelType: 'Diesel',
    remark: '2wheels',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '016',
    registrationNumber: 'CG 07 BP 2411',
    type: 'E-Rikshaw',
    manufacturer: '',
    brand: '',
    status: 'Out of Order',
    fuelType: 'Electric',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '017',
    registrationNumber: 'CG02 AU 0033',
    type: 'MUV',
    manufacturer: 'Isuzu',
    brand: '',
    status: '',
    fuelType: 'Petrol',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '018',
    registrationNumber: 'CG04 HB 8271',
    type: 'Sedan',
    manufacturer: 'TATA',
    brand: 'Indigo',
    status: 'Out of Order',
    fuelType: 'Petrol',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '019',
    registrationNumber: 'CG04 H 1534',
    type: 'Sedan',
    manufacturer: 'Hyundai',
    brand: 'Elantra',
    status: 'Out of Order',
    fuelType: 'Petrol',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '020',
    registrationNumber: 'CG04 H 2213',
    type: 'Hatchback',
    manufacturer: 'Maruti',
    brand: 'Alto',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '021',
    registrationNumber: 'CG04 E 0663',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '022',
    registrationNumber: 'CG07 9419',
    type: 'MUV',
    manufacturer: 'TATA',
    brand: 'Sumo',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
  VehicleModel(
    vehicleId: '023',
    registrationNumber: 'CG07 9822',
    type: 'MUV',
    manufacturer: 'Mahindra',
    brand: 'Max',
    status: 'Out of Order',
    fuelType: 'Diesel',
    owner: 'CSVTU',
    driverId: '',
    imageUrl: '',
  ),
];
